//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Company.MobileDSL
{
	/// <summary>
	/// DomainModel MobileDSLDomainModel
	/// Description for Company.MobileDSL.MobileDSL
	/// </summary>
	[DslDesign::DisplayNameResource("Company.MobileDSL.MobileDSLDomainModel.DisplayName", typeof(global::Company.MobileDSL.MobileDSLDomainModel), "Company.MobileDSL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.MobileDSL.MobileDSLDomainModel.Description", typeof(global::Company.MobileDSL.MobileDSLDomainModel), "Company.MobileDSL.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("12c4d6b9-0218-476d-bfd5-4060bfe71e9c")]
	public partial class MobileDSLDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// MobileDSLDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x12c4d6b9, 0x0218, 0x476d, 0xbf, 0xd5, 0x40, 0x60, 0xbf, 0xe7, 0x1e, 0x9c);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public MobileDSLDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(MobileAppModel),
				typeof(ExampleElement),
				typeof(Controller),
				typeof(State),
				typeof(DataLink),
				typeof(ShowForm),
				typeof(GraphicElement),
				typeof(Input),
				typeof(Label),
				typeof(ServiceInvoke),
				typeof(ServiceMsg),
				typeof(AppCode),
				typeof(MobileAppModelHasElements),
				typeof(ExampleElementReferencesTargets),
				typeof(MobileAppModelHasControllers),
				typeof(MobileAppModelHasStates),
				typeof(MobileAppModelHasDataLinked),
				typeof(MobileAppModelHasShowFormed),
				typeof(ShowFormHasGraphicElements),
				typeof(MobileAppModelHasServiceInvoked),
				typeof(MobileAppModelHasServiceMsg),
				typeof(MobileAppModelHasAppCoded),
				typeof(MobileDSLDiagram),
				typeof(ExampleConnector),
				typeof(ExampleShape),
				typeof(ControllerShape),
				typeof(StateShape),
				typeof(DataLinkShape),
				typeof(ShowFormShape),
				typeof(GraphicElementShape),
				typeof(InputShape),
				typeof(LabelShape),
				typeof(ServiceInvokeShape),
				typeof(ServiceMsgShape),
				typeof(AppCodeShape),
				typeof(ShowFormCompartmentShape),
				typeof(global::Company.MobileDSL.FixUpDiagram),
				typeof(global::Company.MobileDSL.ConnectorRolePlayerChanged),
				typeof(global::Company.MobileDSL.CompartmentItemAddRule),
				typeof(global::Company.MobileDSL.CompartmentItemDeleteRule),
				typeof(global::Company.MobileDSL.CompartmentItemRolePlayerChangeRule),
				typeof(global::Company.MobileDSL.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::Company.MobileDSL.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(ExampleElement), "Name", ExampleElement.NameDomainPropertyId, typeof(ExampleElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Controller), "Name", Controller.NameDomainPropertyId, typeof(Controller.NamePropertyHandler)),
				new DomainMemberInfo(typeof(State), "Name", State.NameDomainPropertyId, typeof(State.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DataLink), "Name", DataLink.NameDomainPropertyId, typeof(DataLink.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ShowForm), "Name", ShowForm.NameDomainPropertyId, typeof(ShowForm.NamePropertyHandler)),
				new DomainMemberInfo(typeof(GraphicElement), "Name", GraphicElement.NameDomainPropertyId, typeof(GraphicElement.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ServiceInvoke), "Name", ServiceInvoke.NameDomainPropertyId, typeof(ServiceInvoke.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ServiceMsg), "Name", ServiceMsg.NameDomainPropertyId, typeof(ServiceMsg.NamePropertyHandler)),
				new DomainMemberInfo(typeof(AppCode), "Name", AppCode.NameDomainPropertyId, typeof(AppCode.NamePropertyHandler)),
				new DomainMemberInfo(typeof(AppCode), "Text", AppCode.TextDomainPropertyId, typeof(AppCode.TextPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(MobileAppModelHasElements), "MobileAppModel", MobileAppModelHasElements.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasElements), "Element", MobileAppModelHasElements.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(ExampleElementReferencesTargets), "Source", ExampleElementReferencesTargets.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(ExampleElementReferencesTargets), "Target", ExampleElementReferencesTargets.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasControllers), "MobileAppModel", MobileAppModelHasControllers.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasControllers), "Controller", MobileAppModelHasControllers.ControllerDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasStates), "MobileAppModel", MobileAppModelHasStates.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasStates), "State", MobileAppModelHasStates.StateDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasDataLinked), "MobileAppModel", MobileAppModelHasDataLinked.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasDataLinked), "DataLink", MobileAppModelHasDataLinked.DataLinkDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasShowFormed), "MobileAppModel", MobileAppModelHasShowFormed.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasShowFormed), "ShowForm", MobileAppModelHasShowFormed.ShowFormDomainRoleId),
				new DomainRolePlayerInfo(typeof(ShowFormHasGraphicElements), "ShowForm", ShowFormHasGraphicElements.ShowFormDomainRoleId),
				new DomainRolePlayerInfo(typeof(ShowFormHasGraphicElements), "GraphicElement", ShowFormHasGraphicElements.GraphicElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasServiceInvoked), "MobileAppModel", MobileAppModelHasServiceInvoked.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasServiceInvoked), "ServiceInvoke", MobileAppModelHasServiceInvoked.ServiceInvokeDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasServiceMsg), "MobileAppModel", MobileAppModelHasServiceMsg.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasServiceMsg), "ServiceMsg", MobileAppModelHasServiceMsg.ServiceMsgDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasAppCoded), "MobileAppModel", MobileAppModelHasAppCoded.MobileAppModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(MobileAppModelHasAppCoded), "AppCode", MobileAppModelHasAppCoded.AppCodeDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(26);
				createElementMap.Add(typeof(MobileAppModel), 0);
				createElementMap.Add(typeof(ExampleElement), 1);
				createElementMap.Add(typeof(Controller), 2);
				createElementMap.Add(typeof(State), 3);
				createElementMap.Add(typeof(DataLink), 4);
				createElementMap.Add(typeof(ShowForm), 5);
				createElementMap.Add(typeof(GraphicElement), 6);
				createElementMap.Add(typeof(Input), 7);
				createElementMap.Add(typeof(Label), 8);
				createElementMap.Add(typeof(ServiceInvoke), 9);
				createElementMap.Add(typeof(ServiceMsg), 10);
				createElementMap.Add(typeof(AppCode), 11);
				createElementMap.Add(typeof(MobileDSLDiagram), 12);
				createElementMap.Add(typeof(ExampleConnector), 13);
				createElementMap.Add(typeof(ExampleShape), 14);
				createElementMap.Add(typeof(ControllerShape), 15);
				createElementMap.Add(typeof(StateShape), 16);
				createElementMap.Add(typeof(DataLinkShape), 17);
				createElementMap.Add(typeof(ShowFormShape), 18);
				createElementMap.Add(typeof(GraphicElementShape), 19);
				createElementMap.Add(typeof(InputShape), 20);
				createElementMap.Add(typeof(LabelShape), 21);
				createElementMap.Add(typeof(ServiceInvokeShape), 22);
				createElementMap.Add(typeof(ServiceMsgShape), 23);
				createElementMap.Add(typeof(AppCodeShape), 24);
				createElementMap.Add(typeof(ShowFormCompartmentShape), 25);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Company.MobileDSL.MobileDSLDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new MobileAppModel(partition, propertyAssignments);
				case 1: return new ExampleElement(partition, propertyAssignments);
				case 2: return new Controller(partition, propertyAssignments);
				case 3: return new State(partition, propertyAssignments);
				case 4: return new DataLink(partition, propertyAssignments);
				case 5: return new ShowForm(partition, propertyAssignments);
				case 6: return new GraphicElement(partition, propertyAssignments);
				case 7: return new Input(partition, propertyAssignments);
				case 8: return new Label(partition, propertyAssignments);
				case 9: return new ServiceInvoke(partition, propertyAssignments);
				case 10: return new ServiceMsg(partition, propertyAssignments);
				case 11: return new AppCode(partition, propertyAssignments);
				case 12: return new MobileDSLDiagram(partition, propertyAssignments);
				case 13: return new ExampleConnector(partition, propertyAssignments);
				case 14: return new ExampleShape(partition, propertyAssignments);
				case 15: return new ControllerShape(partition, propertyAssignments);
				case 16: return new StateShape(partition, propertyAssignments);
				case 17: return new DataLinkShape(partition, propertyAssignments);
				case 18: return new ShowFormShape(partition, propertyAssignments);
				case 19: return new GraphicElementShape(partition, propertyAssignments);
				case 20: return new InputShape(partition, propertyAssignments);
				case 21: return new LabelShape(partition, propertyAssignments);
				case 22: return new ServiceInvokeShape(partition, propertyAssignments);
				case 23: return new ServiceMsgShape(partition, propertyAssignments);
				case 24: return new AppCodeShape(partition, propertyAssignments);
				case 25: return new ShowFormCompartmentShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10);
				createElementLinkMap.Add(typeof(MobileAppModelHasElements), 0);
				createElementLinkMap.Add(typeof(ExampleElementReferencesTargets), 1);
				createElementLinkMap.Add(typeof(MobileAppModelHasControllers), 2);
				createElementLinkMap.Add(typeof(MobileAppModelHasStates), 3);
				createElementLinkMap.Add(typeof(MobileAppModelHasDataLinked), 4);
				createElementLinkMap.Add(typeof(MobileAppModelHasShowFormed), 5);
				createElementLinkMap.Add(typeof(ShowFormHasGraphicElements), 6);
				createElementLinkMap.Add(typeof(MobileAppModelHasServiceInvoked), 7);
				createElementLinkMap.Add(typeof(MobileAppModelHasServiceMsg), 8);
				createElementLinkMap.Add(typeof(MobileAppModelHasAppCoded), 9);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Company.MobileDSL.MobileDSLDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new MobileAppModelHasElements(partition, roleAssignments, propertyAssignments);
				case 1: return new ExampleElementReferencesTargets(partition, roleAssignments, propertyAssignments);
				case 2: return new MobileAppModelHasControllers(partition, roleAssignments, propertyAssignments);
				case 3: return new MobileAppModelHasStates(partition, roleAssignments, propertyAssignments);
				case 4: return new MobileAppModelHasDataLinked(partition, roleAssignments, propertyAssignments);
				case 5: return new MobileAppModelHasShowFormed(partition, roleAssignments, propertyAssignments);
				case 6: return new ShowFormHasGraphicElements(partition, roleAssignments, propertyAssignments);
				case 7: return new MobileAppModelHasServiceInvoked(partition, roleAssignments, propertyAssignments);
				case 8: return new MobileAppModelHasServiceMsg(partition, roleAssignments, propertyAssignments);
				case 9: return new MobileAppModelHasAppCoded(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Company.MobileDSL.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return MobileDSLDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (MobileDSLDomainModel.resourceManager == null)
				{
					MobileDSLDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(MobileDSLDomainModel).Assembly);
				}
				return MobileDSLDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return MobileDSLDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return MobileDSLDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (MobileDSLDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new MobileDSLCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					MobileDSLDomainModel.copyClosure = copyFilter;
				}
				return MobileDSLDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (MobileDSLDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new MobileDSLDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					MobileDSLDomainModel.removeClosure = removeFilter;
				}
				return MobileDSLDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::Company.MobileDSL.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::Company.MobileDSL.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MobileDSLDeleteClosure : MobileDSLDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MobileDSLDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MobileDSLDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public MobileDSLDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasElements.ElementDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasControllers.ControllerDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasStates.StateDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasDataLinked.DataLinkDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasShowFormed.ShowFormDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.ShowFormHasGraphicElements.GraphicElementDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasServiceInvoked.ServiceInvokeDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasServiceMsg.ServiceMsgDomainRoleId, true);
			DomainRoles.Add(global::Company.MobileDSL.MobileAppModelHasAppCoded.AppCodeDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MobileDSLCopyClosure : MobileDSLCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MobileDSLCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class MobileDSLCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public MobileDSLCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

