//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.MobileDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "mdsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MobileDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MobileDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MobileDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMobileDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MobileDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string MobileDSLPackageId = "df025375-5a3e-45d9-922a-bed1a1758715";
		
		// Editor factory identifier
		public const string MobileDSLEditorFactoryId = "0149bfcf-1f11-49f5-a346-12949a958aab";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MobileDSLModelExplorerToolWindowId = "49d1de65-d378-436e-b5b6-4aea405fb6e9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.MobileDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MobileDSLCommandSetId = "3bd1084e-18ca-452e-8891-68524baf05a7";
	}
}