//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace Company.MobileDSL
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\15.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(MobileDSLExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(MobileDSLExplorerToolWindow), Constants.MobileDSLEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@MobileDSLToolboxTab;Company.MobileDSL.Dsl.dll", "Company.MobileDSL.MobileDSLToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ServiceToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ServiceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CreateExampleClassF1Keyword", 
					"@ServiceToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ExampleRelationshipToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ExampleRelationshipToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectExampleRelationF1Keyword", 
					"@ExampleRelationshipToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ControllerToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ControllerToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Controller", 
					"@ControllerToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@StateToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StateToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"State", 
					"@StateToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@DataLinkToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.DataLinkToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DataLink", 
					"@DataLinkToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ShowFormToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ShowFormToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ShowForm", 
					"@ShowFormToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@InputToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.InputToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Input", 
					"@InputToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@LabelToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.LabelToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Label", 
					"@LabelToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@AppCodeToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.AppCodeToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AppCode", 
					"@AppCodeToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@StateFormToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StateFormToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StateForm", 
					"@StateFormToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ButtonToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ButtonToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Button", 
					"@ButtonToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@DropBoxToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.DropBoxToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"DropBox", 
					"@DropBoxToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ListBoxToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ListBoxToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ListBox", 
					"@ListBoxToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@ControllerStateReferenceToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ControllerStateReferenceToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ControllerStateReference", 
					"@ControllerStateReferenceToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@SwitchStateToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.SwitchStateToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SwitchState", 
					"@SwitchStateToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@PortToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.PortToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Port", 
					"@PortToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@SwitchPortToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.SwitchPortToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SwitchPort", 
					"@SwitchPortToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@PortStateConnectToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.PortStateConnectToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"PortStateConnect", 
					"@PortStateConnectToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 17)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@StatePortConnectToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StatePortConnectToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StatePortConnect", 
					"@StatePortConnectToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 18)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSLToolboxTab",
					"@StateConnectorToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.StateConnectorToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"StateConnector", 
					"@StateConnectorToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 19)]
	[VSShell::ProvideStaticToolboxGroup("@MobileDSL2ToolboxTab;Company.MobileDSL.Dsl.dll", "Company.MobileDSL.MobileDSL2ToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSL2ToolboxTab",
					"@SwStateToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.SwStateToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SwState", 
					"@SwStateToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 20)]
	[VSShell::ProvideStaticToolboxItem("Company.MobileDSL.MobileDSL2ToolboxTab",
					"@ConnectionTool1ToolboxItem;Company.MobileDSL.Dsl.dll", 
					"Company.MobileDSL.ConnectionTool1ToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConnectionTool1", 
					"@ConnectionTool1ToolboxBitmap;Company.MobileDSL.Dsl.dll", 
					0xff00ff,
					Index = 21)]
	[VSShell::ProvideEditorFactory(typeof(MobileDSLEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(MobileDSLEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(MobileDSLEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"MobileDSL", typeof(MobileDSLEditorFactory))]

	internal abstract partial class MobileDSLPackageBase : DslShell::ModelingPackage
	{
		protected global::Company.MobileDSL.MobileDSLToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new MobileDSLEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::Company.MobileDSL.MobileDSLToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			MobileDSLCommandSet commandSet = new MobileDSLCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			MobileDSLClipboardCommandSet clipboardCommandSet = new MobileDSLClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(MobileDSLExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace Company.MobileDSL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::Company.MobileDSL.MobileDSLDirectiveProcessor), global::Company.MobileDSL.MobileDSLDirectiveProcessor.MobileDSLDirectiveProcessorName, "A directive processor that provides access to MobileDSL files")]
	[global::System.Runtime.InteropServices.Guid(Constants.MobileDSLPackageId)]
	internal sealed partial class MobileDSLPackage : MobileDSLPackageBase
	{
	}
}